services:
  - type: web
    name: django-multisite
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && \
      gunicorn app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: SECRET_KEY
        value: mpi_(@k!s!yd$fk-%lvmlvafq!a0ky0n%l(s2f_cbnq&s4z3&=
      - key: ALLOWED_HOSTS
        value: django-multisite.onrender.com
      - key: DEBUG
        value: False

  - type: cron
    name: run-migrate-once
    schedule: "@once"
    env: python
    buildCommand: ""
    startCommand: |
      python manage.py migrate && \
      python manage.py collectstatic --noinput && \
      gunicorn app.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: SECRET_KEY
        value: mpi_(@k!s!yd$fk-%lvmlvafq!a0ky0n%l(s2f_cbnq&s4z3&=
      - key: ALLOWED_HOSTS
        value: django-multisite.onrender.com
      - key: DEBUG
        value: False